{% set name = "dash-table" %}
{% set filename = "dash_table" %}
{% set version = "4.11.0" %}
{% set sha256 = "3170504a8626a9676b016c5ab456ab8c1fb1ea0206dcc2eddb8c4c6589216304" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ filename }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python ==2.7.*|>=3.3
    - pip
  run:
    - python ==2.7.*|>=3.3
    - dash

test:
  imports:
    - dash_table

about:
  home: https://dash.plot.ly/datatable
  dev_url: https://github.com/plotly/dash-table
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A First-Class Interactive DataTable for Dash

extra:
  recipe-maintainers:
    - dkucharc
    - moorepants
