{% set name = "dash-table" %}
{% set filename = "dash_table" %}
{% set version = "4.6.0" %}
{% set sha256 = "d30cd8f2212134a576c131f00d403fc6b5ef54579106178fc8d6309500539f07" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ filename }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dash

test:
  imports:
    - dash_table

about:
  home: https://dash.plot.ly/datatable
  dev_url: https://github.com/plotly/dash-table
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A First-Class Interactive DataTable for Dash'

extra:
  recipe-maintainers:
    - dkucharc
    - moorepants
