{% set name = "dash-table" %}
{% set filename = "dash_table" %}
{% set version = "4.0.0" %}
{% set sha256 = "103765284f6437556e9dc99e05929411f3a9b813a05aeee81af34f1bcba099ed" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ filename }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dash

test:
  imports:
    - dash_table

about:
  home: https://dash.plot.ly/datatable
  dev_url: https://github.com/plotly/dash-table
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A First-Class Interactive DataTable for Dash'

extra:
  recipe-maintainers:
    - dkucharc
    - moorepants
